<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <RootNamespace>Template.Library</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <PropertyGroup>
    <TemplateLibraryGeneratorValue>Hello from test project.</TemplateLibraryGeneratorValue>
  </PropertyGroup>

  <Import Project="..\Template.Library.targets" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="SourceGenerateHelper.Testing" Version="1.28.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.Library.Generator\Template.Library.Generator.csproj" OutputItemType="analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Template.Library.Generator\Template.Library.Generator.csproj" ReferenceOutputAssembly="true" />
    <ProjectReference Include="..\Template.Library\Template.Library.csproj" />
  </ItemGroup>

</Project>
